// pages/api/buildQueue.js

export default function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ ok: false, error: "Only POST allowed" });
  }

  try {
    const { csvText, folderId, settings } = req.body || {};

    console.log("buildQueue called:", {
      folderId,
      csvLen: csvText ? csvText.length : 0,
      settings
    });

    // TODO: yahan asli logic aayega:
    // - CSV parse
    // - Runway assets match
    // - motion/camera/prompt generate
    // For now: dummy queue (demo)
    const queue = [
      {
        assetName: "demo_image_1.jpg",
        prompt: "Demo prompt for image 1 generated by Vercel backend"
      },
      {
        assetName: "demo_image_2.jpg",
        prompt: "Demo prompt for image 2 generated by Vercel backend"
      }
    ];

    return res.status(200).json({
      ok: true,
      queue,
      info: {
        folderId: folderId || null,
        total: queue.length,
        settings: settings || {}
      }
    });
  } catch (err) {
    console.error("buildQueue error:", err);
    return res.status(500).json({ ok: false, error: "Server error" });
  }
}
