// pages/api/buildQueue.js

export default function handler(req, res) {
  // Allow only POST requests
  if (req.method !== "POST") {
    return res.status(405).json({ ok: false, error: "Only POST allowed" });
  }

  try {
    const { csvText, folderId, settings } = req.body || {};

    console.log("============================================");
    console.log("   /api/buildQueue HIT from Extension");
    console.log("   CSV Length:", csvText?.length || 0);
    console.log("   Folder ID:", folderId || "none");
    console.log("   Settings:", settings || {});
    console.log("============================================");

    const queue = [];

    // ------------------------------
    // 1) CSV PARSING (simple version)
    // ------------------------------
    if (csvText && typeof csvText === "string") {
      const lines = csvText
        .split(/\r?\n/)
        .map((l) => l.trim())
        .filter(Boolean);

      if (lines.length > 1) {
        const header = lines[0]
          .split(",")
          .map((h) => h.trim().toLowerCase());

        const cleanIdx = header.indexOf("cleanname");
        const promptIdx = header.indexOf("prompt");

        for (let i = 1; i < lines.length; i++) {
          const row = lines[i].split(",");
          const clean = row[cleanIdx]?.trim() || "";
          const prompt = row[promptIdx]?.trim() || "";

          if (clean && prompt) {
            queue.push({
              cleanName: clean,
              prompt
            });
          }
        }
      }
    }

    // --------------------------------------
    // 2) FALLBACK DEMO QUEUE (if CSV empty)
    // --------------------------------------
    if (queue.length === 0) {
      queue.push({
        cleanName: "demo_item_1",
        prompt: "Demo prompt from Vercel (no CSV supplied)."
      });
      queue.push({
        cleanName: "demo_item_2",
        prompt: "Another demo item generated by backend."
      });
    }

    // --------------------------------------
    // 3) FINAL RESPONSE
    // --------------------------------------
    return res.status(200).json({
      ok: true,
      total: queue.length,
      queue,
      folderId: folderId || null,
      settings: settings || {}
    });

  } catch (err) {
    console.error("buildQueue Error:", err);
    return res.status(500).json({
      ok: false,
      error: "Server Error: " + err.message
    });
  }
}
